#paramaeter for the thrusters on the boat

main_propulsion_1:
  id: 1
  position: [-1,-0.5,0.3]                   # the position of the thruster form CO (the forces are poisitve in the direction according to the SNAME-notation)
  type: propeller_with_rudder               # (str) [propeller_fixed, propeller_variable_rudder
  propeller:
    type: fpp
    Kt0: 0.55  
    diameter: 0.2                           # the prop diameter in meters
    max_rpm: 2000
    min_rpm: 0
    rpm_time_constant: 0.3
    pitch_time_constant: 0.5
    wake_factor: 0.05

main_propulsion_2:
  id: 2
  position: [-1,0.5,0.3]                    # the position of the thruster form CO (the forces are poisitve in the direction according to the SNAME-notation)
  type: propeller_with_rudder               # (str) [propeller_fixed, propeller_variable_rudder]
  propeller:
    type: fpp
    Kt0: 0.55 
    diameter: 0.2                           # the prop diameter in meters
    max_rpm: 2000
    min_rpm: 0
    rpm_time_constant: 0.3
    pitch_time_constant: 0.5
    wake_factor: 0.05

